# Generated by Django 4.0.6 on 2022-07-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(default=8, max_length=50),
            preserve_default=False,
        ),
    ]
