# Generated by Django 4.0.6 on 2022-07-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0003_course_fek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fek',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
