# Generated by Django 4.0.6 on 2022-07-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0004_alter_course_fek'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cresource',
            field=models.FileField(blank=True, default='', upload_to='media'),
        ),
    ]
