# Generated by Django 4.0.6 on 2022-07-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0007_teacher_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cresource',
            field=models.FileField(blank=True, default='', upload_to='media/media'),
        ),
    ]
