# Generated by Django 4.0.6 on 2022-07-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0014_alter_student_edc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isteacher',
            field=models.CharField(blank=True, default='n', max_length=5),
        ),
    ]
