# Generated by Django 4.0.6 on 2022-07-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0015_course_isteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isteacher',
            field=models.CharField(blank=True, default='n', max_length=5),
        ),
    ]
